## UID 106082225, Sarvari Pidaparty, MSBA'23

Self - Assessment: I have done the required exercises and fully understand them.

# 6.3 What Does This Code Do?
The dictionary temperatures contains three Fahrenheit temperature samples for each of four days. What does the for statement do?
       
       temperatures = {
           'Monday': [66, 70, 74],
           'Tuesday': [50, 56, 64],
           'Wednesday': [75, 80, 83],
           'Thursday': [67, 74, 81]
           }
       for k, v in temperatures.items():
           print(f'{k}: {sum(v)/len(v):.2f}')

The `for` statement prints out the average of the three temperature samples for each of the days of the week. Further, the temperatures are formatted to 2 decimal places. Below is the output:  

In [1]:
temperatures = {
           'Monday': [66, 70, 74],
           'Tuesday': [50, 56, 64],
           'Wednesday': [75, 80, 83],
           'Thursday': [67, 74, 81]
           }
for k, v in temperatures.items():
    print(f'{k}: {sum(v)/len(v):.2f}')

Monday: 70.00
Tuesday: 56.67
Wednesday: 79.33
Thursday: 74.00


#

# 6.6 Duplicate Word Removal
Write a function that receives a list of words, then determines and displays in alphabetical order only the unique words. Treat uppercase and lowercase letters the same. The function should use a set to get the unique words in the list. Test your function with several sentences.

In [2]:
def dupwords(words):
    list1 = []
    for i in words:
        if i.lower() not in list1:
            list1.append(i)      
    list1.sort()
    return list1

In [3]:
dupwords(['order','mess','random','mess'])

['mess', 'order', 'random']

In [4]:
dupwords(['i','am','a','graduate','student','at','a','top','university'])

['a', 'am', 'at', 'graduate', 'i', 'student', 'top', 'university']

Function `dupwords` creates a list of the non-duplicate items in the entered list. We use a simple `for` loop to accomplish this task. For every item in the entered list, we check if it is already present in the new list we are creating. If it is not present, we add the item to our new list. Then we return our newly created list with no duplicates.

#

# 6.9 Dictionary Manipulations
Using the following dictionary, which maps country names to Internet top-level domains (TLDs):

       tlds = {'Canada': 'ca', 'United States': 'us', 'Mexico': 'mx'}

perform the following tasks and display the results:  
a) Check whether the dictionary contains the key 'Canada'.  
b) Check whether the dictionary contains the key 'France'.  
c) Iterate through the key–value pairs and display them in two-column format.  
d) Add the key–value pair 'Sweden' and 'sw' (which is incorrect).  
e) Update the value for the key 'Sweden' to 'se'.  
f) Use a dictionary comprehension to reverse the keys and values.  
g) With the result of part(f), use a dictionary comprehension to convert the country names to all uppercase letters.

In [5]:
tlds = {'Canada': 'ca', 'United States': 'us', 'Mexico': 'mx'}
'Canada' in tlds #a

True

`True` is returned so we know the dictionary contains the key `Canada`.

In [6]:
'France' in tlds #b

False

`False` is returned, hence the dictionary does not contain the key `France`.

In [7]:
print(f'        Country    |     Code')
for country, code in tlds.items():
    print(f'{country:>15} {code:>11}') #c

        Country    |     Code
         Canada          ca
  United States          us
         Mexico          mx


A simple `for` loop is executed to access the keys and values in `tlds`, which are printed in a column format using the format statement.

In [8]:
tlds['Sweden'] = 'sw'
tlds #d

{'Canada': 'ca', 'United States': 'us', 'Mexico': 'mx', 'Sweden': 'sw'}

Simple syntax to add a new key and value to an existing dictionary.

In [9]:
tlds['Sweden'] = 'se'
tlds #e

{'Canada': 'ca', 'United States': 'us', 'Mexico': 'mx', 'Sweden': 'se'}

Similar syntax as (d) to update value in the dictionary.

In [10]:
tlds_rev = {code:country for country, code in tlds.items()}
tlds_rev #f

{'ca': 'Canada', 'us': 'United States', 'mx': 'Mexico', 'se': 'Sweden'}

Using `dictionary comprehension`, we unpack the keys and tuples by iterating through them and the expression code:country reverses the key-value tuple.

In [11]:
tlds_g = {code:country.upper() for code, country in tlds_rev.items()}
tlds_g #g

{'ca': 'CANADA', 'us': 'UNITED STATES', 'mx': 'MEXICO', 'se': 'SWEDEN'}

#

# 7.2 Broadcasting
Use arange to create a 2-by-2 array containing the numbers 0–3. Use broadcasting to perform each of the following operations on the original array:  
a) Cube every element of the array.  
b) Add 7 to every element of the array.  
c) Multiply every element of the array by 2.

In [12]:
import numpy as np
num = np.arange(0, 4).reshape(2,2)
num 

array([[0, 1],
       [2, 3]])

In [13]:
num**3 #a

array([[ 0,  1],
       [ 8, 27]])

In [14]:
num + 7 #b

array([[ 7,  8],
       [ 9, 10]])

In [15]:
num*2 #c

array([[0, 2],
       [4, 6]])

`Arange` is used to first create a 2 by 2 array with numbers 0-3. 
Array arithmetic operations are used to accomplish the mentioned tasks - cube, add and multiply to the original array.

#

# 7.3 Element-Wise Array Multiplication
Create a 3-by-3 array containing the even integers from 2 through 18. Create a second 3-by-3 array containing the integers from 9 down to 1, then multiply the first array by the second.

In [16]:
import numpy as np
array1 = np.arange(1,10).reshape(3,3)
array2 = array1 * 2
array3 = np.arange(9,0,-1).reshape(3,3)
array2 * array3

array([[18, 32, 42],
       [48, 50, 48],
       [42, 32, 18]])

`array2` is created by multiplying `array1` by 2 - which is created using `arange` to generate a 3x3 array with numbers 1 through 9.
`array3` is created using `arange` as well, but counting down from 9 to 0.
The arrays are then simple multiplied to obtain the result.

#

# 7.9 Indexing and Slicing arrays
Create an array containing the values 1–15, reshape it into a 3-by-5 array, then use indexing and slicing techniques to perform each of the following operations:  
a) Select row 2.  
b) Select column 5.  
c) Select rows 0 and 1.  
d) Select columns 2–4.  
e) Select the element that is in row 1 and column 4.  
f) Select all elements from rows 1 and 2 that are in columns 0, 2 and 4.

In [17]:
import numpy as np
arrayind = np.arange(1,16).reshape(3,5)
arrayind

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [18]:
arrayind[1] #a

array([ 6,  7,  8,  9, 10])

In [19]:
arrayind[:,4] #b

array([ 5, 10, 15])

In [20]:
arrayind[0:2] #c (assumed indices 0 to 2)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [21]:
arrayind[:,1:3] #d

array([[ 2,  3],
       [ 7,  8],
       [12, 13]])

In [22]:
arrayind[0,3] #e

4

In [23]:
arrayind[0:2,[0,2,4]] #f

array([[ 1,  3,  5],
       [ 6,  8, 10]])

#

# 7.14 Horizontal and Vertical Stacking
Create the two-dimensional arrays 

        array1 = np.array([[0, 1], [2, 3]])

        array2 = np.array([[4, 5], [6, 7]])

a) Use vertical stacking to create the 4-by-2 array named array3 with array1 stacked on top of array2.  
b) Use horizontal stacking to create the 2-by-4 array named array4 with array2 to the right of array1.  
c) Use vertical stacking with two copies of array4 to create a 4-by-4 array5.  
d) Use horizontal stacking with two copies of array3 to create a 4-by-4 array6.

In [24]:
array1 = np.array([[0, 1], [2, 3]])
array2 = np.array([[4, 5], [6, 7]])

In [25]:
array3 = np.vstack((array1, array2))
array3 #a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [26]:
array4 = np.hstack((array1, array2))
array4 #b

array([[0, 1, 4, 5],
       [2, 3, 6, 7]])

In [27]:
array5 = np.vstack((array4, array4))
array5 #c

array([[0, 1, 4, 5],
       [2, 3, 6, 7],
       [0, 1, 4, 5],
       [2, 3, 6, 7]])

In [28]:
array6 = np.hstack((array3, array3))
array6 #d

array([[0, 1, 0, 1],
       [2, 3, 2, 3],
       [4, 5, 4, 5],
       [6, 7, 6, 7]])

`np.vstack` and `np.hstack` are used to stack arrays as per each question.